// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBjYlNhiqs2NhyNSG6jJM5x6DIdlJ-98',
    appId: '1:269507769785:web:6359d4dc4eb853035eb268',
    messagingSenderId: '269507769785',
    projectId: 'figapp-b53cc',
    authDomain: 'figapp-b53cc.firebaseapp.com',
    storageBucket: 'figapp-b53cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnsXxxd9-_YB75n0YKFDjeOp2TrxDp00',
    appId: '1:269507769785:android:f0c7af1056d1a1f85eb268',
    messagingSenderId: '269507769785',
    projectId: 'figapp-b53cc',
    storageBucket: 'figapp-b53cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuS-AN1Wi2FcwiVf2M98slMZAkyGNrQ1I',
    appId: '1:269507769785:ios:61e46abe18cba27d5eb268',
    messagingSenderId: '269507769785',
    projectId: 'figapp-b53cc',
    storageBucket: 'figapp-b53cc.firebasestorage.app',
    iosBundleId: 'com.example.figapp',
  );
}
